# Generated by Django 3.1 on 2020-09-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=200)),
                ('producto_descripcion', models.TextField()),
                ('producto_ingreso', models.DateField(verbose_name='fecha de ingreso')),
                ('producto_salida', models.DateField(verbose_name='fecha de salida')),
                ('producto_cliente', models.CharField(max_length=200)),
            ],
        ),
    ]
